### ISSUE TITLE
mongoreplay play outputs `context.Execute error: error executing op: Closed explicitly`

### ISSUE THREAD

**Issue by mtsmfm** [mongodb-labs/mongoreplay#3]
Does this tool replay the same amount of operations even if I got this message?
If so, I think I can ignore this message though.

## How to reproduce

1. Download this file https://mtsmfm.s3-ap-northeast-1.amazonaws.com/mongoreplay/test.playback.gz

2. Run the following command:

```
$ bin/mongoreplay play --speed 10 -p test.playback.gz --host mongo --gzip
```

https://gist.github.com/mtsmfm/38ec676b4119104a309745c7c321e829

## Environment

golang:1.14.3-buster

Here's the VSCode remote container setting with docker-compose.yml

https://github.com/mtsmfm/mongoreplay/commit/b6c6e58a4c73548b44e9b705a2b90875781cca97

## Additional info

I recorded this playback with the following queries:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'mongo'
end

connection_count = 2000
loop_count = 1000

Mongo::Logger.logger.level = Logger::WARN
client = Mongo::Client.new("mongodb://mongo/testing", max_pool_size: connection_count, min_pool_size: connection_count)

collection = client['numbers']

collection.drop

connection_count.times do |index|
  collection.insert_one(index: index, value: 0)
end

threads = connection_count.times.map do |i|
  Thread.new(i) do |index|
    loop_count.times do |n|
      collection.update_one({index: index}, {value: n})
    end
  end
end

threads.each(&:join)
```

**Comment by rychipman** [comment]
Hi @mtsmfm, `mongoreplay` is no longer actively maintained or supported. I'm going to close this issue, and archive the repo to make this more clear for the future.
