### ISSUE TITLE
mongoreplay play feature doesnt seem to support secondarypreferred option

### ISSUE THREAD

**Issue by neerajwadhwani** [mongodb-labs/mongoreplay#5]
When trying to play the playback file on a secondary it didnt seem to work. Does it not support or am I missing something in the connection string?

--host mongodb://Admin:pwd@127.0.0.1:27017/?authSource=admin&readPreference=secondaryPreferred

--host mongodb://Admin:pwd@127.0.0.1:27017/?replicaSet=replica1&authSource=admin&readPreference=secondaryPreferred

**Comment by rychipman** [comment]
Hi @neerajwadhwani, `mongoreplay` is no longer actively maintained or supported. I'm going to close this issue, and archive the repo to make this more clear for the future.
